// SysTick.c
// Runs on TM4C123
// Starter file for CECS346 Project 2
// By Dr. Min He

#include "tm4c123gh6pm.h"
#include <stdint.h> // C99 data types
#include "SysTick.h" 

// Initialize SysTick timer with priority 3.
// Dependencies: NVIC_SYS_PRI3_R, NVIC_ST_CTRL_R
void SysTick_Init(void) {
	NVIC_ST_CTRL_R = 0;         	// disable SysTick during setup
	//                             clear the 3 bits | set 31-29                                  
  NVIC_SYS_PRI3_R = (NVIC_SYS_PRI3_R & 0x1FFFFFFF)|0x60000000; // priority is the first three binary digits{3} === bits 31-29 ===
	NVIC_ST_CTRL_R |= NVIC_ST_CTRL_CLK_SRC|NVIC_ST_CTRL_INTEN;	// enable interupt SysTick with core clock and interrupts (7)
}

// Start systick timer with specified reload value.
// Parameter "period" specifies number of counts for the time period generated by systick timer.
// It takes one parameter, 'period', which specifies the number of counts for the time period. based on FSM
void SysTick_Start(uint32_t period) {	
	NVIC_ST_RELOAD_R = period -1;		// reload value 12500000-1	period is the amount of cycles of half seconds we want to perform
  NVIC_ST_CURRENT_R = 0;      		// any write to current clears it
	NVIC_ST_CTRL_R |= NVIC_ST_CTRL_ENABLE;	// enable interupt SysTick with core clock and interrupts (7)
}

// Stop the Systick timer by disabling the timer
void SysTick_Stop(void) {
		NVIC_ST_CTRL_R &= ~NVIC_ST_CTRL_ENABLE;       // Stop the Systick by disabling it with = 0
}
